### ISSUE TITLE
why x*255

### ISSUE THREAD

**Issue by azuryl** [Caoang327/vis_det#3]
https://github.com/Caoang327/vis_det/blob/0b544cee20bb304b27bac6d9e64d3bac6b4b6b4b/vis_det/optimize/optimize.py#L54

  losses = model.vis(x * 255, gt_instances, scale_weight=self.scale_weight)

**Comment by Caoang327** [comment]
Hi:

sorry for late response. The input to the network is [-255, 255] if I remember correctly.
